# Generated by Django 5.2.10 on 2026-02-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('heritage_seeker', 'HERITAGE_SEEKER'), ('curious_traveller', 'CURIOUS_TRAVELLER'), ('cultural_explorar', 'CULTURAL_EXPLORAR')], default='heritage_seeker', max_length=20),
        ),
    ]
