# Generated by Django 5.2.10 on 2026-02-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('driver', 'Driver'), ('provider', 'Service Provider'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
