# Generated by Django 5.2.10 on 2026-02-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'FREE'), ('community', 'COMMUNITY'), ('preparation', 'PREPARATION'), ('premium', 'PREMIUM')], default='free', max_length=20),
        ),
    ]
