# Generated by Django 5.2.10 on 2026-02-10 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=7)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_sessions', to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_guide.budgetstyle')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSessionBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accommodation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('experiences', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='budget_guide.budgetsession')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_user_id', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='budget_guide.budgetsession')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSessionExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_guide.budgetexperience')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_experiences', to='budget_guide.budgetsession')),
            ],
            options={
                'unique_together': {('session', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flights', 'Flights'), ('accommodation', 'Accommodation'), ('transportation', 'Transportation'), ('food', 'Food'), ('experiences', 'Experiences'), ('emergency', 'Emergency Buffer')], max_length=30)),
                ('min_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='budget_guide.budgetstyle')),
            ],
            options={
                'unique_together': {('style', 'category')},
            },
        ),
    ]
